### ISSUE TITLE
Allow config to target CSS selectors for extraction

### ISSUE THREAD

**Issue by jamieshark** [jamieshark/i18n-html_extractor#4]
Since there are a few instances where there might be a class like `.sr-only`, we should ensure that these get translated.

**Comment by francisfuzz** [comment]
For posterity, `.sr-only` is Primer's [`Screen reader only`](https://primer.style/css/utilities/layout/#screen-reader-only) utility class. It's used for positioning an element outside of the viewport for screen reader access only. 

Considering this example snippet using `.sr-only` class:

```html
<div class="js-details-container Details">
  <button type="button" class="btn">Tab once from this button, and press enter</button>
  <button type="button" class="sr-only js-details-target">
    Screen reader only button
  </button>
  <div class="Details-content--hidden">
    Button activated!
  </div>
</div>
```

If we wrote a CSS selector matcher to find `.sr-only`, we would need to teach it to identify the text in that node. Yet, I'm wondering if the [PlainTextMatch](https://github.com/jamieshark/i18n-html_extractor/blob/main/lib/i18n/html_extractor/match/plain_text_match.rb) would just end up capturing that "Screen reader only button" already since it "looks" like a hard-coded string?

**Comment by jamieshark** [comment]
Closing in favor of https://github.com/github/dotcom-i18n/issues/34
